//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Melyon.Resources.Scene
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object
    {
        public int Objects_ID { get; set; }
        public string Objects_Name { get; set; }
        public string Objects_Script { get; set; }
    }
}
